### ISSUE TITLE
Store build system information

### ISSUE THREAD

**Issue by martindurant** [conda/constructor#130]
Constructor currently stored the absolute set of of packages (URL/version/hash) in a file `pkgs/urls` within the tarball. This is great! However, that is not all that affects the binary that is produced; I would like to see another file alongside with the information on the system that produced it, including versions of constructor, python, conda and platform information.

**Comment by kalefranz** [comment]
@mingwandroid @nehaljwani Basically Martin is asking for some of the details of `constructor --test` to be included in the installer somewhere--or in a file created by the installer after it's ran.  Do either of you have opinions on where it should go?  For conda packages, we have `conda_version` and `conda_build_version`, along with a few other things, in the `info/about.json` file.

I don't think we can put it in a `conda-meta/XXX.json` file, because I think all current versions of conda expects each `*.json` file in `conda-meta/` to represent a package.

We could probably put it in `conda-meta/history` if we were careful.  And in fact, constructor should probably be writing the history file correctly anyway.

I guess by including this information in `conda-meta/history`, I proposing something like

```
==> 2017-11-07 12:28:46 <==
# cmd: /Users/kfranz/continuum/conda/conda/__main__.py create -n _newer python constructor -c defaults
# constructor: {"constructor_version": "2.0.0", "conda_interface_type": "conda", "conda_interface_version": "4.3.30"}
+defaults::xz-5.2.3-ha24016e_1
+defaults::yaml-0.1.7-hff548bb_1
+defaults::zlib-1.2.11-h60db283_1
# create specs: python,constructor
```

The new part here is the `constructor:` line.  But I guess I'm also advocating here that constructor should be including all the relevant information in the `conda-meta/history` file.  This will be especially important starting for conda 4.4, when conda starts to treat different packages that result from an explicit user-supplied spec, and packages that are brought in as dependencies to satisfy requirements.

Thoughts?

**Comment by nehaljwani** [comment]
You mentioned 'conda_interface_type' in the proposal, which makes me think. @mingwandroid, should we remove all remnants of the code which still refers to libconda?

**Comment by kalefranz** [comment]
I agree in general with re-opening this issue.  What I proposed in the above comment has several elements that goes beyond what was done in #134.  Perhaps we should open a new issue entirely?

**Comment by martindurant** [comment]
Recommend new issue, this certainly was enough for what I originally had in mind - but the more system information the better!

**Comment by kalefranz** [comment]
I think we can close this issue in lieu of #138 and #139.
