### ISSUE TITLE
Error: File 'Library' found in multiple packages

### ISSUE THREAD

**Issue by speleo3** [conda/constructor#132]
constructor 2.0.0 fails on Windows with this error message:

```
Checking for duplicate files ...
Error: File 'Library' found in multiple packages: qt-5.6.2-vc9_6.tar.bz2, icu-57
.1-vc9_0.tar.bz2
```

"Library" is a directory, so it should be ignored in any file duplication checks.

Adding "ignore_duplicate_files: True" to constructor.yaml yields:

```
Checking for duplicate files ...
Warning: File 'Library' found in multiple packages: qt-5.6.2-vc9_6.tar.bz2, icu-
57.1-vc9_0.tar.bz2
Warning: File 'Library/lib' found in multiple packages: qt-5.6.2-vc9_6.tar.bz2,
icu-57.1-vc9_0.tar.bz2
Warning: File 'Library/include' found in multiple packages: qt-5.6.2-vc9_6.tar.b
z2, icu-57.1-vc9_0.tar.bz2
Warning: File 'Library/bin' found in multiple packages: qt-5.6.2-vc9_6.tar.bz2,
icu-57.1-vc9_0.tar.bz2
```

**Comment by forman** [comment]
Same issue here. With Constructor 2.0.1 I get

    Checking for duplicate files ...
    Error: File 'Library/COPYING' found in multiple packages: hdf4-4.2.13-vc14_0.tar.bz2, hdf5-1.10.1-vc14_1.tar.bz2

Thanks to the secret weapon `ignore_duplicate_files` I get:

    Checking for duplicate files ...
    Warning: File 'Library/COPYING' found in multiple packages: hdf4-4.2.13-vc14_0.tar.bz2, hdf5-1.10.1-vc14_1.tar.bz2
    Warning: File 'Library/RELEASE.txt' found in multiple packages: hdf4-4.2.13-vc14_0.tar.bz2, hdf5-1.10.1-vc14_1.tar.bz2

I agree with @joelhullcio to mention this in [CONSTRUCT.md](https://github.com/conda/constructor/blob/master/CONSTRUCT.md). Thanks!

**Comment by mingwandroid** [comment]
@forman this is *not* the same issue. The issue was a bug where directories were not being filtered out from this 'same-file' check. 

It is fatal if two packages ever contain the same files and this error is there to prevent making such broken installers.

For people who don't care about broken installers you can use `ignore_duplicate_files: True` but that's not the right thing to do. These packages mutually break each other and neither should contain these files (they should instead identify their license files in their metadata).

**Comment by forman** [comment]
@mingwandroid 

> this is not the same issue.
Understood.

> It is fatal if two packages ever contain the same files and this error is there to prevent making broken installers in that case.
It is fatal only if two packages contain files with same path and filenames but are different in content and if the content is eventually important for the software's functionality.

> These packages mutually break each other and neither should contain these files 
I generally agree, but then Constructor should offer finer control about files to be ignored while copying, because `ignore_duplicate_files` is a global setting.
In the case of my `hdf4` and `hdf5` dependencies, I don't care whose `RELEASE.txt` gets copied into some common `Library` folder of my installer, I need both dependencies anyway and I want a workaround for the fact that they unfortunately use a common package structure.

**Comment by mingwandroid** [comment]
> It is fatal only if two packages contain files with same path and filenames but are different in content and if the content is eventually important for the software's functionality.

No you are wrong. It is fatal full stop:

```
conda install package1-containing-a package2-containing-a
conda remove package2-containing-a
```

.. you no longer have a despite still having `package1-containing-a` installed. If `a` is essential to the operation of `package1-containing-a` then your installation is hosed.

The only thing to be done here is to fix you packages.
