### ISSUE TITLE
Windows Start Location

### ISSUE THREAD

**Issue by quasiben** [conda/constructor#222]
This is one of those tough to debug issues on the Windows side.

1- We created an Anaconda Windows installer using ‘constructor’ 2.0.3. It contained some of our custom packages and the “anaconda 5.1.0” metapackage.
2- This was installed as the Admin user to a path on the C drive without spaces or Unicode
3- The installation <sometimes> installs all the shortcuts but most times only installs the Jupyter Notebook shortcut.
4- The Jupyter Notebook shortcut link has ‘Starts In’ set to ‘%HOME%’ which is not a valid location on windows by default. The correct link should be
a. HOMEDRIVE%HOMEPATH%

The problem for us, is that if the location is not set correctly the analysts end up with Jupyter/Anaconda Prompt launched C:\Windows\system32 which freaks most of them out.

**Comment by nehaljwani** [comment]
This problem was most likely fixed in the latest version of menuinst. Could you please update the anaconda metapackage to 5.3.0? That will give you the latest version of menuinst which has this fix.

**Comment by nehaljwani** [comment]
https://github.com/ContinuumIO/menuinst/compare/9d0c28bb2ae8708ddcc05a38f782bc16efb344eb..902a70aafe1856f8e9e3b72c362f0bd980e51cc0#diff-420a6c16906cbc57973d8bc46a8b648eL339

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.

NOTE: also I think Nehal is right, this may be fixed by improvements to menuinst.
