### ISSUE TITLE
Exit code on -h must be zero.

### ISSUE THREAD

**Issue by AXGKl** [conda/constructor#255]
Hi, thanks for constructor.

At least a few recent versions here the exit code is not zero when running `-h` on constructed installers.

In a multistage build script I need to see if that phase finished successfully by testing if the installer had been created. I would prefer a successfull -h run, compared to simply checking the presence of the constructed installer in the FS.

That might easen a few of those issues as well: https://github.com/conda/constructor/issues/131

**Comment by mcg1969** [comment]
The exit code for `-h` as been 2 for as long as this project has been offered. Perhaps @ilanschnell would be willing to share why that particular choice was made, but I would be reluctant to change it without understanding.

That said, because the exit code is specifically 2, you could actually test for that; e.g.,
```
bash installer.sh -h >/dev/null 2>&1
if [ $? != 2 ]; then echo "error creating installer"; fi
```
