### ISSUE TITLE
Error with menu creation on v3 branch

### ISSUE THREAD

**Issue by David-Baddeley** [conda/constructor#262]
When building for windows using the v3 branch (following the instructions in https://github.com/conda/constructor/issues/257 and using conda-4.7.5-win-64.exe from https://repo.anaconda.com/pkgs/misc/conda-execs/) we run into the following error during installation:

![image](https://user-images.githubusercontent.com/19475296/62569528-cf353080-b8e2-11e9-839f-98e87480c1b1.png)

Interestingly, however, the menus appear to be installed correctly despite this error. 

I can't find conda.exe.py in either the constructor or conda repositories, and mk_menus in constructor/nsis/_nsis.py  (the only place in both projects I could find a matching function) has the right signature.

Any pointers to help me track this down would be much appreciated. Thanks for all the hard work!

**Comment by msarahan** [comment]
conda.exe.py is a file that is used to create the standalone installer.  We're behind, but you can now see it at https://github.com/AnacondaRecipes/conda-standalone-feedstock/blob/master/recipe/conda.exe.py

It looks like the problem is here: https://github.com/AnacondaRecipes/conda-standalone-feedstock/blob/master/recipe/conda.exe.py#L95

We can't debug this right now, but if you figure it out, a PR would be most welcome.

**Comment by msarahan** [comment]
This was fixed as part of the latest standalone conda: https://github.com/AnacondaRecipes/conda-standalone-feedstock/commit/f979a2c6fd6db615c472994d9038ecd7f774efec
