### ISSUE TITLE
Support local file:///-based channels

### ISSUE THREAD

**Issue by dsentinel** [conda/constructor#269]
Using constructor to build an installer with a locally built and hosted package like this:
```yaml
...
channels:
  - file:///Users/builder/miniconda3/conda-bld
  - https://conda.anaconda.org/conda-forge
  - http://repo.anaconda.com/pkgs/main/
...
```
No longer works.

On install, the local channel is not found as it is a path on the machine the constructor was created.
```
$ bash pkg-2019.219-MacOSX-x86_64.sh

Welcome to pkg 2019.219

pkg will now be installed into this location:
/Users/installer/pkg_env

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/Users/installer/pkg_env] >>>
PREFIX=/Users/installer/pkg_env
Unpacking payload ...
Collecting package metadata (current_repodata.json): ...working... failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: conda-bld
  channel url: file:///Users/builder/miniconda3/conda-bld
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. Use `conda index /Users/lloyd/miniconda3/conda-bld`, or create `noarch/repodata.json`
and associated `noarch/repodata.json.bz2`.
```

conda 4.7.11
constructor 3.0.0

**Comment by astaric** [comment]
I have the same problem. Opened #276 with the change I use, soI can create the installer.

**Comment by astaric** [comment]
@nehaljwani, in my case, there is no place to remap the local channel to. I build installer from local packages since these packages are not available anywhere else.

**Comment by msarahan** [comment]
Reopening.  We are encountering this in building Anaconda installers, where the anaconda metapackage is not available on any public channel yet.  I think the best way to do it is probably to create the $PREFIX/conda-bld folder, populate it with these local file URLs, and copy the files in there.  We'll have to pre-generate the index in there as well, so that conda-build is not a requirement for each installer, or alternatively make a standalone executable that includes conda-build.

**Comment by scottwsides** [comment]
Just want to say that this fix is very much needed. I've kind of lost track of the status of this as its mentioned in several places. Is the fix for using local channels and having a pkg work on other machines in place? Has the conda constructor package on anaconda been updated? Or... should I use the GitHub current download?

**Comment by mcg1969** [comment]
I'm going to mark this as an enhancement but someone is going to have to step up and do some creative engineering here! So consider this a call out to the community for help.

I think Nehal's idea points to a solution:
> Please use channel_remap for remapping local channels.
Now I totally understand the response:
> The package doesn't exist on a public channel, so no sensical remap destination.
But just because there isn't a sensible channel to remap to, doesn't mean one can't be _invented_ simply to get this to work.

And if it can be confirmed that creating a "nonsensical" public channel to remap to solves the problem, we can actually find a way to do that more automatically inside the code itself.

**Comment by mcg1969** [comment]
#286 looks very close but we need it to work for .exe and .pkg installers as well, of course.

**Comment by nylocx** [comment]
Hi, after reading through this and some related issues I'm still not sure if there is a way to include local wheels into the installation on Windows. Using `file://C:\something` in spec is not working, neither was my try in using a full https url provided by a simple pypi compatible repo. I read that there should be a way using local channels with remapping but I could not find any examples or documentation on that.

Currently I use a workaround by running a .bat script manually after the install to add my own packages into the conda environment, but that is very far from optimal. I open for any suggestions to solve this.

Kind regards and thanks for this great tool.

**Comment by benpapworth** [comment]
Some of the issues reported here might be resolved by checking the file URL created by conda.common.url.path_to_url matches the file URL in the constructor.yaml, as it's quite hard to accurately hand code a URL that will exactly matches the URL that is internally used by Conda.

https://github.com/conda/constructor/issues/416
