### ISSUE TITLE
different python3 minor version between Unix/Windows

### ISSUE THREAD

**Issue by jschueller** [conda/constructor#303]
If I specify only the python 3 major version in the construct.yaml:
```
specs:
  - python 3.*
```
Then the resulting installer has python 3.7.x on Linux/OSX, and 3.6.x on Windows,
eventhough I install constructor from a fresh miniconda3 install that defaults to python 3.7.x on all 3 platforms.
Why the different behavior ?

Here's the full construct.yaml:
```
name: otconda3
version: 1.13

ignore_duplicate_files: true
install_in_dependency_order: true

channels:
  - https://conda.anaconda.org/conda-forge/
  - https://repo.continuum.io/pkgs/free/
  - https://repo.continuum.io/pkgs/main/
  - https://repo.continuum.io/pkgs/r/
  - https://repo.continuum.io/pkgs/pro/
  - https://repo.continuum.io/pkgs/msys2/  [win]

specs:
  - python 3.*
  - conda
  - console_shortcut  [win]
  - menuinst  [win]

license_file: EULA.txt
welcome_image: galton_v.png
header_image: galton_h.png
icon_image: icon256.png
```

**Comment by hobu** [comment]
Constructor adds `python` to the dependencies. https://github.com/conda/constructor/blob/master/constructor/fcp.py#L168

**Comment by mcg1969** [comment]
I suspect this is because there were not Python 3.7 versions of one or more of the Windows-specific dependencies available at the time; e.g., menuinst or console_shortcut or one of their dependencies. That said constructor is technically not wrong here. It's just using conda to resolve the environment. Conda was given permission to consider a python 3.6.

I am going to close this, but if the issue persists, I would suggest it is a conda issue.
