### ISSUE TITLE
Use Ensure Conda (optionally)

### ISSUE THREAD

**Issue by goanpeca** [conda/constructor#392]
It would be nice to use https://github.com/conda-incubator/ensureconda to get the conda (or mamba) executable to use for solving the envs.

This would not add a dependency on the package, but if it was found, it would be used.

I can work on this :-) 

Thoughts @mcg1969 ?

**Comment by mcg1969** [comment]
I'm not sure I understand the benefit of this. Can you explain more precisely the problem this would actually solve? At the moment, the conda executable is already specified by a dependency on `conda_standalone`, so when this package is installed with conda you already have a default executable available. And of course, conda itself is a dependency of consructor, so that is guaranteed to be available. If you want to specify an alternative standalone executable you can with the `--conda-exe` option.

**Comment by mcg1969** [comment]
@goanpeca as you can see I've been doing some issue pruning. I'm inclined to close this _unless_ we can come up with specific uses cases where this would be specifically useful, or concrete issues that this would solve, and put them here.

Even if we _do_ close this it wouldn't preclude you from working on it! I just want to try and limit the open issues to ones that are a bit more concrete.

Thoughts?

**Comment by goanpeca** [comment]
Hi @mcg1969, ensure conda deals with both conda and mamba/micromamba executable.

**Comment by mcg1969** [comment]
I know what ensureconda does, but I don't see why it is helpful here. Conda is a dependency of constructor, and we don't build pip packages of this. So we are certain conda exists in the environment. If you want to use mamba for the solve, you can, but you still need the standalone executable conda.exe to embed in to the installer—and ensureconda doesn't provide that.

**Comment by mcg1969** [comment]
In fact, not only does constructor expect conda to be in the PATH, it actually _imports_ from it.

**Comment by goanpeca** [comment]
>it actually imports from it.

True!

@scopatz any thoughts you would like to include :-) ?

**Comment by mcg1969** [comment]
I hope it is clear, if ensureconda can be useful in this context I welcome it. I don't see it yet but I absolutely could be missing something! If you think a PR can be built that might serve as its own explanation.

**Comment by scopatz** [comment]
My only comment is that I think the import issue is unavoidable at this point.
