### ISSUE TITLE
Conda clean --all should also clean the cached constructor packages

### ISSUE THREAD

**Issue by strets123** [conda/constructor#45]
When using constructor the packages are cached in $HOME/.conda/constructor

This folder is not cleaned out by the conda clean command build logically it perhaps should be.

Also, when updating a local conda channel using conda index if the updated package has the same name as a previous package then conda constructor does not allow it to be overwritten

**Comment by mcg1969** [comment]
I know this issue is very old! Trying to do some cleanup.
`constructor --clean` cleans up the constructor cache. I don't agree it should be `conda`'s responsibility to do this.
Your point about `conda index` is definitely an interesting one, but seems like a corner case. However, because this issue is so old and constructor has been significantly refactored I'm not convinced it's still operative. I'm going to close this but please feel free to open a new issue if you find it occurring with the latest versions of constructor.
