### ISSUE TITLE
Add back Post-install and pre-install scripts

### ISSUE THREAD

**Issue by bkreider** [conda/constructor#5]
I notice that there is no way to run post/pre install scripts which are often necessary.

**Comment by ilanschnell** [comment]
What are the use cases for these post/pre install scripts?

**Comment by bheklilr** [comment]
@ilanschnell I can see a use case for allowing pre-install scripts to ensure that the system is compatible with packages being installed.  For example, I may want to include a conda package that binds to additional 3rd party libraries or drivers that can't be distributed for licensing or technical reasons.  The pre-install script could try to look for these additional dependencies and if not present show a message box warning the user that certain packages may not function properly.

For post-install what immediately springs to mind is adding desktop and start menu shortcuts to applications shipped with a constructor-built installer.  It could also be used to automatically set up additional conda environments such as for setting up dev environments for an entire team consistently, or for starting an included application after the installer is finished.  I can come up with more examples if you'd like more justification.

**Comment by ilanschnell** [comment]
https://github.com/conda/constructor/commit/f50a41c5ba248c43695778515dfe6d73e4fc7c0e add this ability on Unix.

**Comment by ilanschnell** [comment]
At some point, I want to add something similar to Windows also.

**Comment by bheklilr** [comment]
I'd be willing to take a look at the Unix implementation tomorrow and seeing if I can port it to Windows. Windows is our main platform and this feature would be useful that I can justify spending time on it.

**Comment by ilanschnell** [comment]
The Windows implementation is more complicated (not surprisingly).  Which type of scripts should be supported on Windows?  `.bat` or `.py`?  It would be quite easy to support Python *post* install scripts on Windows (I could do that in less than an hour).  Pre install (at least Python) scripts would not work (in general, obviously).

**Comment by bheklilr** [comment]
I think it should be kept consistent with `conda build` which expects a `bld.bat`.  Pretty much every `bld.bat` I've written consists of only calling `%PYTHON% setup.py install`, so at least for post-install users can just call out to a python script in the same style (or any other kind of executable for that matter), and if it's needed for pre-install then the `.bat` script can check to see if `python.exe` is available before trying anything.  It's also consistent with Unix since it uses the default shell environment.

One thing to look out for is that the user may choose to leave a particular conda install off the path, so a post-install `.bat` script would benefit from having a `%PYTHON%` variable injected into its environment so that it can be called with the correct Python executable.  I imagine this is how `conda build` handles it, too.

**Comment by kawing-chiu** [comment]
+1 for this (although closed at the moment).
