### ISSUE TITLE
Bug: using a packages file and the conda package in specs fails

### ISSUE THREAD

**Issue by joelhullcio** [conda/constructor#55]
The attached example construct.yaml file will fail to build.
If the conda entry under specs is commented out then the build will work.

If the user builds the specs file from a conda env using conda list --explicit it cannot include conda since conda isn't installed in envs.  Adding conda to the specs section causes the constructor build to fail.  This issue prevents a user from adding to conda to an installer when using a packages files.

Also, adding conda-build to the specs section will cause that same issue.  

This failed with constructor version 1.5.1

[construct.yaml.txt](https://github.com/conda/constructor/files/697379/construct.yaml.txt)
[specs.txt](https://github.com/conda/constructor/files/697380/specs.txt)

**Comment by ilanschnell** [comment]
Having everything in `specs.txt` (including `conda`) works for me.
The `construct.yaml` is just:
```
name: test
version: 1.0.0
packages: specs.txt
```
Also, when you create an environment which starts with `_`, you can install conda into it without problems:
```
$ conda create -n _testconda python=2.7 conda
```
Environments with `_` don't have the "conda not allowed" restriction.

**Comment by mcg1969** [comment]
Sorry for the form message—I'm doing some issue cleanup and closing some issues that are likely to be stale because they were opened for constructor 2.x or earlier. Constructor 3.x is significantly different in operation, and many of the issues raised for 2.x are either not relevant or significantly modified. Please feel free to open a  new issue if you feel that 3.x still suffers from this problem.
