### ISSUE TITLE
fix windows releases, failing with no descriptive error code

### ISSUE THREAD

**Issue by joamatab** [conda/constructor#585]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

windows releases are failing now

https://github.com/gdsfactory/gdsfactory/actions/runs/3516082345/jobs/5892172732

https://github.com/gdsfactory/gdsfactory/issues/904

**Comment by joamatab** [comment]
Here is another failed built, it does not seem reproducible

https://github.com/gdsfactory/gdsfactory/actions/runs/3576871549/jobs/6015215286

**Comment by jaimergp** [comment]
Exit 143 is SIGTERM, probably sent by the operating system because the process was using too many resources. I guess this is RAM usage, and the fact that it passes on macOS makes it even more likely, since macOS VMs on GHA have more memory assigned than Windows and Linux.

I don't think this is directly related to constructor itself. The env you are trying to solve might be too complex for `conda` to handle.

You could try `constructor` as available on `main`, which has support for additional solvers up to conda 22.9. That means you can install `conda-libmamba-solver` to use `libmamba` behind the scenes and use less memory for the solves.

Support for conda 22.11 plugin-style solvers is not available on `constructor` yet, so make sure you stick to conda 22.9 tops if you want to try this route.

**Comment by joamatab** [comment]
Hi Jaime,

thank you for pointing the memory issue

removing spyder from `construct.yml` solved the issue

https://github.com/gdsfactory/gdsfactory/actions/runs/3677791511
