### ISSUE TITLE
Add SSL CA verify option to file

### ISSUE THREAD

**Issue by bkreider** [conda/constructor#64]
Add a way to specify the SSL CA root when running against a Repo using SSL.

**Comment by krake-r** [comment]
I came across this one today. Annoying having to drop SSL to make it work.

**Comment by nehaljwani** [comment]
Could you try:
```
export REQUESTS_CA_BUNDLE=/path/to/ca/certificate/or/bundle
```
Or, in Windows:
```
set REQUESTS_CA_BUNDLE=/path/to/ca/certificate/or/bundle
```

**Comment by bkreider** [comment]
Where would one set those variables so that the tornado server process picked them up?

**Comment by nehaljwani** [comment]
I don't understand. constructor uses conda which uses requests to make all the http requests. How does tornado come into the picture?

**Comment by bkreider** [comment]
Sorry, i thought my initial report covered the bigger issue that krake-r is talking about.  The Repo Server (tornado) embeds constructor and calls out to it.  From Anaconda Server, one needs a way to set the CA bundle that will be used when it calls out to constructor to create installers and parcels.

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.

@bkreider in particular because of the way constructor now uses conda directly, I think we're covered.
