### ISSUE TITLE
how do those installers interact with python and conda environments?

### ISSUE THREAD

**Issue by stunlocked1** [conda/constructor#648]
I like the idea but will those for example appear in vscode interpreters? Or is it like an actual package that is self contained

**Comment by jaimergp** [comment]
This the project powering your Miniconda/Miniforge installers. So it will look like one more conda installation. I am not sure but I think VS Code knows how to find them too (I've seen them in my machine while doing some local tests).

**Comment by JoerivanEngelen** [comment]
I can confirm that an installer built with constructor will create a conda environment which is found by VSCode (at least on Windows). 

Tip (on Windows): Make sure no other Python/Conda environments are in your PATH environmental variable, because this easily creates a dependency mess with the wrong .dll files loading.
