### ISSUE TITLE
Don't unset LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by bkreider** [conda/constructor#65]
https://github.com/conda/constructor/blob/master/constructor/header.sh#L13
```
unset LD_LIBRARY_PATH
```

Or at least store it as a new name so pre/post install scripts can use binaries.

**Comment by ilanschnell** [comment]
Yes, of course pre/post install scripts can use binaries, and the installer uses them also.  Using binaries is not the problem.  Relying on `LD_LIBRARY_PATH` is the problem.  No properly linked binary should every require `LD_LIBRARY_PATH` to be set.  `LD_LIBRARY_PATH` should only be used by experts during development or debugging, and creating an installer is not for that purpose, it is for production deployment.

**Comment by mingwandroid** [comment]
@bkreider are you saying that your post install scripts need to use (e.g. weird non-system) binaries built outside of conda-build that rely on setting `LD_LIBRARY_PATH`?

**Comment by bkreider** [comment]
@mingwandroid The way the customer has installed some system binaries in their *production* system the AEN installer requires LD_LIBRARY_PATH during pre/post install.  I didn't realizer that conda cared about ENV variables during the pre and post install steps.  I thought it was just shelling out at that point?  

If the AEN teams wants to be able to install there, I guess they will need to fork, so we can make this more robust and able to access the variable inside of pre/post install. 

```
OLD_LD_LIBRARY_PATH=LD_LIBRARY_PATH
unset LD_LIBRARY_PATH
```

**Comment by mingwandroid** [comment]
> the AEN installer requires LD_LIBRARY_PATH during pre/post install

Do you know which parts of the installer require `LD_LIBRARY_PATH` to be set? Is it a standard `conda` package or a bespoke one?

Having `LD_LIBRARY_PATH` set during pre/post install can for sure break us, in a site-specific way. It all depends on what shared libraries are in that path and which shared libraries are needed by the binaries that the pre/post install wants to run. It's not that conda cares, it's the Linux dynamic loader that cares.

This is really murky, the *best* way is for no one to ever use `LD_LIBRARY_PATH`. If the customer can set `RPATH`s in their executables so that the necessary shared libraries get found through that (much more robust) mechanism instead then that is my recommendation.

Given you are going suggesting `OLD_LD_LIBRARY_PATH=LD_LIBRARY_PATH`, I guess these are bespoke packages that you're going to modify the post install for? If they are bespoke packages, can they not be built to use `RPATH`?

**Comment by bkreider** [comment]
> Given you are going suggesting OLD_LD_LIBRARY_PATH=LD_LIBRARY_PATH, I guess these are bespoke packages that you're going to modify the post install for? If they are bespoke packages, can they not be built to use RPATH?

The call to the system provided `mongo` was breaking (this is to check the prerequisites) .  The reason I wanted to hold onto the old library path is that the pre/post install could then temporarily set the LD_LIBRARY_PATH for system calls and unset it after the call.  Right now there is no way to get through the install.  I have no idea why their system needed it to work.

**Comment by mingwandroid** [comment]
Sounds like needs must then I guess.

Rather than setting and unsetting, the cleanest way would be:

`LD_LIBRARY_PATH=$OLD_LD_LIBRARY_PATH mongo .. blah blah blah`

**Comment by ilanschnell** [comment]
In https://github.com/conda/constructor/commit/7d4f106311331086383570f5463c527606d1959b,
I've added storing the old `LD_LIBRARY_PATH` as `OLD_LD_LIBRARY_PATH`, such that a post install script can say
```
export LD_LIBRARY_PATH=$OLD_LD_LIBRARY_PATH
```
if necessary.

**Comment by bkreider** [comment]
Great!  Thanks.
