### ISSUE TITLE
fail with better error message

### ISSUE THREAD

**Issue by joamatab** [conda/constructor#653]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

How could we fail with a more descriptive error messages?

https://github.com/gdsfactory/gdsfactory/actions/runs/4276066747/jobs/7443895099

**Comment by joamatab** [comment]
I tried both pinning conda or enforcing constructor version and the issue persists

https://github.com/gdsfactory/gdsfactory/actions/runs/4396097366/jobs/7698325611

it's interesting that it still builds on windows

**Comment by dbast** [comment]
Seems like with a completely different error... not able to resolve dependencies.

Can you replace the line in https://github.com/gdsfactory/gdsfactory/actions/runs/4396097366/jobs/7698325611
* `conda install "constructor>=3.4.2" -y` with e.g. `conda create --name constructor "constructor>=3.4.2" -y` instead of installing into an existing environment.

Also then requires a `conda activate constructor` before running constructor.
