### ISSUE TITLE
Feature request:  MSI installers on Windows

### ISSUE THREAD

**Issue by janssen** [conda/constructor#8]
Not sure whether NSIS supports making MSI installers.

**Comment by mcg1969** [comment]
Unfortunately, NSIS does not support the creation of MSI installers.
https://stackoverflow.com/questions/1858434/build-nsis-script-as-a-msi-package
That's not to say it can't be done—in fact, one of the answers on the above link points to a tool that wraps EXE installers in MSI wrappers as a workaround. But the right solution is to use something like [WiX](https://wixtoolset.org/) instead.
I'm not going to close this because it's an absolutely legitimate request—but it's not something the existing team is going to be able to do. It would require someone from the community stepping up. And it might also require that someone build conda packages for the WiX toolset.

**Comment by janssen** [comment]
I'm aware that NSIS does not support the creation of MSI installers.

And there's no need for WiX or something like it.  Standard CPython
includes a library called "msilib", written by Martin von Löwis, which
contains all the tools needed to write an MSI installer.  I know because
I've used to build MSI installers, twice.

Bill

**Comment by mcg1969** [comment]
That's great to know! Thank you for the info. Hopefully someone will take up this project.
