### ISSUE TITLE
Windows installer CLI option `/S` flag doesn't include any feedback

### ISSUE THREAD

**Issue by pavelzw** [conda/constructor#812]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When running the windows installer with `/S`, as expected, no installation GUI occurs. Instead, I would have expected that there is some feedback, for example the exit code.

Instead, the installer directly exits with exit code 0 and you have no way of knowing apart from opening Task Manager and searching for `python` or `_conda` or your installer running whether the installer is still running or has already finished.

For example, when providing an invalid path with `/D`, it doesn't fail but instead defaults to the default location.

I'm using conda-constructor via `pixi global install constructor` in an isolated environment.

**Comment by marcoesters** [comment]
There are a few issues here that are separate from each other. I will try and address them one-by-one:

> Instead, I would have expected that there is some feedback,

That would indeed be great to forward stdout into the console. I filed an issue in the past about this: https://github.com/conda/constructor/issues/764

> for example the exit code

As far as I'm aware, the exit code will always be 0, unfortunately. The logs are the best way to look for failures. However, log files have issues with installers in production because they write log files into `%USERPROFILE%` when a user hits the "Browse" button.

> Instead, the installer directly exits with exit code 0 and you have no way of knowing apart from opening Task Manager and searching for python or _conda or your installer running whether the installer is still running or has already finished.

I assume you run the installer as `installer.exe /S`? If so, the command line just spawns the process that way without waiting for it. As far as I know, this is normal with calling exe files from `cmd.exe`. The way to run it is `start /wait installer.exe /S`.

> For example, when providing an invalid path with /D, it doesn't fail but instead defaults to the default location.

This is unfortunately standard behavior of NSIS (the Windows installer backend of this project). Alternatives to NSIS have been looked at, but this is a more significant engineering effort to refactor and no solution is perfect: https://github.com/conda/constructor/issues/646

Did that answer your questions?
